flag_0 DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ed1c24h, 0ed1c24h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0000000h, 0000000h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0000000h, 0000000h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0000000h, 0000000h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0000000h, 0000000h, 0000000h, 0000000h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
       DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh

